---
title: "007Mir9_ChIRP_G4_MED1_K27ac_ALL_GREEN_mer"
output: html_document
---

## Programs to load in R
```{r setup, include=FALSE}
library(openxlsx)
library(data.table)
library(edgeR)
library(dplyr)
library(doParallel)
library(BiocParallel)
library(gam)
library(foreach)
library(ggplot2)
library("RcppArmadillo")
library(DESeq2)
library(DelayedArray)
library(RColorBrewer)
library(Rcpp)
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(plyr)
library(gplots)
library(org.Rn.eg.db)
library(EnrichedHeatmap)
library(ComplexHeatmap)
library(tidyr)
library(circlize)
  workdir = "./"
setwd(workdir)
LOGD=-0.58
LOGUP=0.58
LOGU=0.58
LOGD_AT=-0.58
LOGU_AT=0.58
PVALUE=0.05
CCTR="#f6e8c3"
CCKO= "#762a83"

Actrcol= c("black","black")
Akocol=c("violet","violet")
Actrcol2= c("gray","gray")
Akocol2=c("deeppink","deeppink")
Actrcol3= c("blue","blue")
Akocol3=c("gold","gold")
Actrcol4= c("coral4","coral4")
Akocol4=c("darkgreen","darkgreen")
G1<- c("C1","C2","ES_KO1","ES_KO2")

LOGD2=-0.32
LOGU2=0.32
AA<- "../fromR_Allu_enh"
dir.create(AA)
PORT="../fromR_Allu_enh/007Mir9_ChIRP_G4_MED1_K27ac_ALL_GREEN_mer/"
PORT1="../fromR_Allu_enh/007Mir9_ChIRP_G4_MED1_K27ac_ALL_GREEN_mer/"
dir.create(PORT1)
#install.packages('DelayedArray', dep = TRUE)
PROJECT="007Mir9_ChIRP_G4_MED1_K27ac_ALL_GREEN_mer"
PROJECT2="007Mir9_ChIRP_G4_MED1_K27ac_ALL_GREEN_mer"
PROJECT3="Mir9_ChIRP_P1e3_ds_RMDvs_MED1_Smarca5_ALL_mm10_ALLDOWN"
PROJECT4="Mir9_ChIRP_P1e3_ds_RMDvs_MED1_Smarca5_ALL_mm10_ALLUP"

U=2000
D=-2000
```


### load M9 in CPC sorted from dob_BGI13_2x2
```{r}
M9 = "../../01_miR-9_ChiRP/02PEAKS/003MERG_D/01p1e3_ds/Mir9_merge_peaks_p1e3_ds_rmd_PEAKS_bedt_d1c2_annot"
cat("Current file name is:",M9,"/n")
mat_M9_sor_ES = read.delim(M9,header=T,check.names=FALSE, stringsAsFactors=FALSE)
name3<- data.frame(colnames(mat_M9_sor_ES))
head (mat_M9_sor_ES)
mat_M9_sor_ES$SYMBOL <- mat_M9_sor_ES$`Gene Name`
#mat_M9_sor_ES <- mat_M9_sor_ES[!duplicated(mat_M9_sor_ES$REFSEQ),]
name9<- data.frame(colnames(mat_M9_sor_ES))
#df2_M9_TSS2 <- subset(mat_M9_sor_ES, `Distance to TSS` >= D &`Distance to TSS` <= U)
#sor_ES_d<- length(unique(df2_M9_TSS2$SYMBOL))
##UP log2FC >= 1.5

df2_M9_TSS2_u <- mat_M9_sor_ES[!duplicated(mat_M9_sor_ES$SYMBOL),]

  MED1 = "../../../../002NCBI_DATA/001ChiP_seq/001MEF_CHIPs/001_SE_TFs/001SELEC_MEF/01Med_MEF_SRR1519931/01PEAKS_MED1/00Med1_MEF_MAC14_p1e2_d100_rmd_peaks_annot"
#MED1 = "/media/heart/KI-MA004/NCBI_MA004/001ChIP_seq/09_3T34_MED1_SNF2H_GSE53585/PEAKS/MED1_343T_MAC14_p1e5_rmd_peaks_annot"

cat("Current file name is:",MED1,"/n")
mat_MED1_sor_ES = read.delim(MED1,header=T,check.names=FALSE, stringsAsFactors=FALSE)
name3<- data.frame(colnames(mat_MED1_sor_ES))
head (mat_MED1_sor_ES)
mat_MED1_sor_ES$SYMBOL <- mat_MED1_sor_ES$`Gene Name`

#mat_MED1_sor_ES <- mat_MED1_sor_ES[!duplicated(mat_MED1_sor_ES$REFSEQ),]
name1<- data.frame(colnames(mat_MED1_sor_ES))
#df2_MED1_TSS2 <- subset(mat_MED1_sor_ES, `Distance to TSS` >= D &`Distance to TSS` <= U)
#sor_MED1<- length(unique(df2_MED1_TSS2$SYMBOL))
##UP log2FC >= 1.5

df2_MED1_TSS2_u <- mat_MED1_sor_ES[!duplicated(mat_MED1_sor_ES$SYMBOL),]

k27ac = "Z:/001_External_Heart_drives/KI-MA004/NCBI_MA004/001_SE_TFs/11_H3k27ac_MEF/MEF_GSM2417093_KLF4/SE_MEF/ENDO_only/FDR05/001_k27ac_endoMEF_v_WCE_FDR05_WITH_TYE_ANNOT"
#k27ac = "/media/heart/KI-MA004/NCBI_MA004/001ChIP_seq/09_3T34_MED1_SNF2H_GSE53585/PEAKS/SMARCA5_343T_MAC14_p1e5_rmd_peaks_annot"

mat_k27ac_sor_ES = read.delim(k27ac,header=T,check.names=FALSE, stringsAsFactors=FALSE)
  name3<- data.frame(colnames(mat_k27ac_sor_ES))
head (mat_k27ac_sor_ES)
mat_k27ac_sor_ES$SYMBOL <- mat_k27ac_sor_ES$`Gene Name`

#mat_k27ac_sor_ES <- mat_k27ac_sor_ES[!duplicated(mat_k27ac_sor_ES$REFSEQ),]
name1<- data.frame(colnames(mat_k27ac_sor_ES))
#df2_k27ac_TSS2 <- subset(mat_k27ac_sor_ES, `Distance to TSS` >= D &`Distance to TSS` <= U)
#sor_k27ac<- length(unique(df2_k27ac_TSS2$SYMBOL))
##UP log2FC >= 1.5

df2_k27ac_TSS2_u <- mat_k27ac_sor_ES[!duplicated(mat_k27ac_sor_ES$SYMBOL),]
RAD21 = "Z:/001_External_Heart_drives/KI-MA004/NCBI_MA004/001_SE_TFs/04_Rad21_mESC_SRR361432/02Rad21_MEF_GSM3040193/PEAKS_Rad21/p1e2_d100/Rad21_MEF_MAC14_p1e2_rmd_d100_peaks_annot"
cat("Current file name is:",RAD21,"/n")
mat_RAD21_sor_ES = read.delim(RAD21,header=T,check.names=FALSE, stringsAsFactors=FALSE)
name3<- data.frame(colnames(mat_RAD21_sor_ES))
head (mat_RAD21_sor_ES)
mat_RAD21_sor_ES$SYMBOL <- mat_RAD21_sor_ES$`Gene Name`

G4 = "Z:/003_NCBI_Data/14_OTHERS/07G4_mmu_Hu_GSE133379/02PEAKS/d30/02G4_3T3_MAC14_p1e3_d30_peaks_annot"
mat_G4_sor_ES = read.delim(G4,header=T,check.names=FALSE, stringsAsFactors=FALSE)
name3<- data.frame(colnames(mat_G4_sor_ES))
head (mat_G4_sor_ES)
mat_G4_sor_ES$SYMBOL <- mat_G4_sor_ES$`Gene Name`
df2_G4_TSS2 <- subset(mat_G4_sor_ES, `Distance to TSS` <= D  |`Distance to TSS` >= U)
df2_G4_TSS2_u <- mat_G4_sor_ES[!duplicated(mat_G4_sor_ES$SYMBOL),]
```

## prepare for matrix
```{r}

A<- data.frame(df2_M9_TSS2_u$SYMBOL)
colnames(A)<- "SYMBOL"
A$IP<- "X01Mir9"


B<- data.frame(df2_MED1_TSS2_u$SYMBOL)
colnames(B)<- "SYMBOL"
B$IP<- "X03MED1"

C<- data.frame(df2_k27ac_TSS2_u$SYMBOL)
colnames(C)<- "SYMBOL"
C$IP<- "X04k27ac"

D<- data.frame(mat_RAD21_sor_ES$SYMBOL)
colnames(D)<- "SYMBOL"
D$IP<- "X05RAD21"

D2<- data.frame(df2_G4_TSS2_u$SYMBOL)
colnames(D2)<- "SYMBOL"
D2$IP<- "X02G4"

ALL<- rbind(A,B,C,D2)
ALLu<- ALL[!duplicated(ALL[,c("SYMBOL","IP")]),]
ALLu22<- ALL[!duplicated(ALL[,c("SYMBOL","IP")]),]

ALLu$IP2<- paste(ALLu$SYMBOL,ALLu$IP,sep="_")
ALLu$SYMBOL<- 1

library(tidyr)
library(stringr)
rownames(ALLu)<- ALLu$IP2
MAT_AA4<- spread(ALLu[,1:3],IP, SYMBOL,fill = 0)
MAT_AA4_1<- MAT_AA4[5:nrow(MAT_AA4),]
MAT_AA4_2<- data.frame(str_split_fixed(MAT_AA4_1$IP2,"_", 2))
colnames(MAT_AA4_2)<- c("SYMBOL","IP")
MAT_AA4_3<- cbind(MAT_AA4_2,MAT_AA4_1)

MAT_AA4_4 <- aggregate(.~SYMBOL, MAT_AA4_3, max)
NAME_SAM2<- c("X01Mir9","X02G4","X03MED1","X04k27ac")
MAT_AA4_5<- subset(MAT_AA4_4,select=c("SYMBOL","X01Mir9","X02G4","X03MED1","X04k27ac"))

colnames(MAT_AA4_5)<- c("SYMBOL",NAME_SAM2)

M9<- data.frame(c("Gata6","Zdhhc5","Lzts2", "Hdac7","Ncl","Ep300"))
colnames(M9)<- c("SYMBOL")
M9$M9_STUDY<- "YES"
M9_1<- merge(MAT_AA4_5,M9,by="SYMBOL")
M9_2<- data.frame(setdiff(MAT_AA4_5$SYMBOL,M9$SYMBOL))
colnames(M9_2)<- c("SYMBOL")
M9_2$M9_STUDY<- "MAYBE"
M9_2<- merge(M9_2,MAT_AA4_5,by="SYMBOL")


MAT_AA4_6<- rbind(M9_1,M9_2)
write.xlsx(MAT_AA4_6,file=paste(PORT1,PROJECT,"_MATRIX_FROM_VENN.xls",sep=""),overwrite = T)

```



```{r}
NAME_SAMP<- NAME_SAM2
MA46c2<- count(MAT_AA4_6, NAME_SAM2)

MA46c2_m9<- subset(MA46c2,X01Mir9==1 | X01Mir9==0 & X02G4==1)


 # MA46c2$FC1[MA46c2$X01Mir9==1& MA46c2$X02G4!=1] <- "M9_Targets"
  MA46c2$FC1[MA46c2$X01Mir9==0] <- "03M9_NO_TARG"
  MA46c2$FC1[MA46c2$X01Mir9==1 & MA46c2$X02G4==1] <- "01M9_G4_Targets"
  MA46c2$FC1[MA46c2$X01Mir9==1 & MA46c2$X02G4==0] <- "02M9_G4_NO_Targets"

  MA46c2$FC2[MA46c2$X01Mir9==0] <-"03M9_NO_TARG"
  MA46c2$FC2[MA46c2$X01Mir9==1 & MA46c2$X03MED1==1] <- "01M9_MED1_Targets"
  MA46c2$FC2[MA46c2$X01Mir9==1 & MA46c2$X03MED1==0] <- "02M9_MED1_NO_Targets"
library(ggalluvial)
library(gridExtra)
CO_ALU=c("#d7191c","#542788","#d8b365","#abd9e9", "#2c7bb6", "#4d4d4d","grey")
#CO_ALU2=c("#d7191c","#d8b365","#542788","#abd9e9", "#2c7bb6", "#4d4d4d","grey")
CO_ALU3=c("#d7191c","#d8b365","#542788","grey", "#91bfdb", "grey","grey")
#CO_ALU=c(CO22_ENH,"grey")
CO_ALU2=c("lightgrey","darkgreen","#542788")
CO_ALU4=c("lightgrey","#d7191c")
CO_ALU1=c("lightgrey","#542788","darkgreen")
XL="IPs samples"
YL="N° of genes"
ALLu22<- ALL[!duplicated(ALL[,c("SYMBOL","IP")]),]
SI=10
AL1<-ggplot(data = MA46c2, aes(y = freq,
             axis1 = X01Mir9, axis2 = X02G4, axis3 = X03MED1, axis4 = X04k27ac)) +
  geom_alluvium(aes(fill = X01Mir9),curve_type = "arctangent") +  geom_stratum(width = 1/4) +  scale_fill_manual(values=CO_ALU2)+ geom_text(stat = "stratum", color="black" , size=1, 
        nudge_y=c(.1,.2,.3,.4,.5,0),aes(label = after_stat(stratum))) +scale_x_continuous(breaks = 1:4,labels = NAME_SAMP) +theme_void()
AL1a<- AL1+labs(title=paste(PROJECT ,"ALL_COMBI",sep="_" ), x=XL, y = YL)+theme(plot.title = element_text(color="black", size=9, face="bold"),axis.text.x = element_text(color="black", size=SI, face="bold"),axis.text.y = element_text(color="#993333", size=SI, face="bold"))+guides(fill =guide_legend(title = "Mir9"))
print(AL1a)

AL2<-ggplot(data = MA46c2, aes(y = freq,
             axis1 = X01Mir9, axis2 = X02G4, axis3 = X03MED1, axis4 = X04k27ac)) +
  geom_alluvium(aes(fill = FC1),curve_type = "arctangent") +  geom_stratum(width = 1/4) +  scale_fill_manual(values=rev(CO_ALU1))+ geom_text(stat = "stratum", color="black" , size=1, 
        nudge_y=c(.1,.2,.3,.4,.5,0),aes(label = after_stat(stratum))) +scale_x_continuous(breaks = 1:4,labels = NAME_SAMP) +theme_void()
AL2a<- AL2+labs(title=paste(PROJECT ,"ALL_COMBI",sep="_" ), x=" ", y = YL)+theme(plot.title = element_text(color="black", size=9, face="bold"),axis.text.x = element_text(color="black", size=SI, face="bold"),axis.text.y = element_text(color="#993333", size=SI, face="bold")) +guides(fill =guide_legend(title = "group"))
print(AL2a)

AL3<-ggplot(data = MA46c2, aes(y = freq,
             axis1 = X01Mir9, axis2 = X02G4, axis3 = X03MED1, axis4 = X04k27ac)) +
  geom_alluvium(aes(fill = FC2),curve_type = "arctangent") +  geom_stratum(width = 1/4) +  scale_fill_manual(values=rev(CO_ALU1))+ geom_text(stat = "stratum", color="black" , size=1, 
        nudge_y=c(.1,.2,.3,.4,.5,0),aes(label = after_stat(stratum))) +scale_x_continuous(breaks = 1:4,labels = NAME_SAMP) +theme_void()
AL3a<- AL3+labs(title=paste(PROJECT ,"ALL_COMBI",sep="_" ), x=" ", y = YL)+theme(plot.title = element_text(color="black", size=9, face="bold"),axis.text.x = element_text(color="black", size=SI, face="bold"),axis.text.y = element_text(color="#993333", size=SI, face="bold")) +guides(fill =guide_legend(title = "group"))
print(AL3a)


AL4<-ggplot(data = MA46c2_m9, aes(y = freq,
             axis1 = X01Mir9, axis2 = X02G4, axis3 = X03MED1, axis4 = X04k27ac)) +
  geom_alluvium(aes(fill = X01Mir9),curve_type = "arctangent") +  geom_stratum(width = 1/4) +  scale_fill_manual(values=CO_ALU2)+ geom_text(stat = "stratum", color="black" , size=1, 
        nudge_y=c(.1,.2,.3,.4,.5,0),aes(label = after_stat(stratum))) +scale_x_continuous(breaks = 1:4,labels = NAME_SAMP) +theme_void()
AL4a<- AL4+labs(title=paste(PROJECT ,"ALL_COMBI",sep="_" ), x=" ", y = YL)+theme(plot.title = element_text(color="black", size=9, face="bold"),axis.text.x = element_text(color="black", size=SI, face="bold"),axis.text.y = element_text(color="#993333", size=SI, face="bold")) +guides(fill =guide_legend(title = "X01Mir9"))
print(AL4a)
pdf(file=paste(PORT, "00_",PROJECT,"_ALLU",".pdf"), width=6, height=4) 
  set.seed(1)
  arrange1b <- ggarrange(AL1a, ncol = 1,nrow =1,common.legend = T, align = c("hv"),legend="top")
print(arrange1b)

#print(AL1a)
 print(AL2a) 
 print(AL3a)
 print(AL4a) 
dev.off()

```



```{r}
require(VennDiagram)
D0=paste(PORT1,"00Venn",PROJECT, "_2.tiff",sep="")
LL=0.03
TT=0.7
PP=c(0.5, 0.80)
PP2=c(0.5, 0.90)
MM=0.35
set.seed(1)
venn.plot <- venn.diagram(
    list(M9 =mat_M9_sor_ES$SYMBOL, C4 = mat_MED1_sor_ES$SYMBOL, k27ac= mat_k27ac_sor_ES$SYMBOL), 
  D0,
  col = "transparent",
  fill = c("darkgreen","cyan","violet"),
  alpha = TT,
  label.col = c("black", "white", "black", "white","white", "white" ,"black" ),
  cex = 1.5,
  fontfamily = "serif",
  fontface = "bold",
  cat.col = c("darkblue", "darkblue", "darkblue"),
  cat.cex = 1.5,
  cat.pos = 0,
  cat.dist = LL,
  cat.fontfamily = "serif",
  rotation.degree = 180,
  margin = MM,
  print.mode="raw",
  hyper.test = T,
    resolution =600,
  main=D0,
    main.cex=1,  main.pos =PP
  
);

D02=paste(PORT1,"00Venn_withG4",PROJECT, ".tiff",sep="")
LL=0.33
TT=0.7
PP=c(0.5, 0.80)
PP2=c(0.5, 0.90)
MM=0.35
set.seed(1)
venn.plot <- venn.diagram(
    list(M9 =mat_M9_sor_ES$SYMBOL, C4 = mat_MED1_sor_ES$SYMBOL, k27ac= mat_k27ac_sor_ES$SYMBO,
         RAD21= mat_RAD21_sor_ES$SYMBOL), 
  D02,
  col = "transparent",
  fill = c("darkgreen","cyan","darkviolet","#ef8a62"),
  alpha = TT,
label.col = c("orange", "white", "darkorchid4", "white", 
                "white", "white", "white", "white", "white", "white", 
                "white", "white", "white", "white", "white"),
  cex = 1.5,
  fontfamily = "serif",
  fontface = "bold",
  cat.col = c("darkblue", "darkgreen", "orange", "darkorchid4"),
  cat.cex = 1.5,
  cat.pos = 0,
  cat.dist = LL,
  cat.fontfamily = "serif",
  rotation.degree = 0,
  margin = MM,
  print.mode="raw",
  hyper.test = T,
    resolution =600,
  main=D0,
    main.cex=1,  main.pos =PP
);

```
### run from here
####### DE genes only Log2FC
```{r}
PNHADs = "../../../../07_Mir9_ChIRP_P1e3_ds_RMDv_PNHDAs/01Mirle7d_PNHADs/03b_176_NADs_3MBs_mergePTomm10_w_GN.bed"
cat("Current file name is:",PNHADs,"/n")
mat_PNHADs_sor_ES = read.delim(PNHADs,header=F,check.names=FALSE, stringsAsFactors=FALSE)
head (mat_PNHADs_sor_ES)
 name4<- c("chr_m9", "start_m9", "end_m9", "chr_P", "start_P", "end_P","Gene Name")
colnames(mat_PNHADs_sor_ES) <- name4
mat_PNHADs_sor_ES$SYMBOL <- mat_PNHADs_sor_ES$`Gene Name`
 mat_PNHADs_sor_PNHDAs <- list(resddBGI13_2_25,mat_PNHADs_sor_ES) %>%
  Reduce(function(dtf1,dtf2) inner_join(dtf1,dtf2,by="Gene Name"), .)


M9_PNHA <- merge(mat_PNHADs_sor_ES,resddBGI13_2_25, by="SYMBOL")
M9_PNHAn<- length(unique(M9_PNHA$`Gene Name`))
##### vs DOWN


DIFF_CP <- rbind(M9_PNHAn)
DIFF_CP
M9_MED1_k27ac_ONLY <- data.frame(setdiff(resddBGI13_2_25$SYMBOL,mat_PNHADs_sor_ES$SYMBOL))
colnames(M9_MED1_k27ac_ONLY) <- "SYMBOL"

#M9_MED1_k27ac_ONLY <- merge(CP1vs_H2Bub_ES_d_FC_P005_MI_H2,resddBGI13_2_25, by="SYMBOL")
M9_MED1_k27ac_ONLY$group <- "02nO_PNHA"
M9_PNHA$group <- "01in_PNHA"
name55<- colnames(M9_MED1_k27ac_ONLY)
M9_PNHA_2 <- subset(M9_PNHA, SYMBOL="", select=c("SYMBOL","group"))

M9_MED1_k27ac_A <- rbind(M9_PNHA_2,M9_MED1_k27ac_ONLY)

 library(biomaRt)
human = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
mouse = useMart("ensembl", dataset = "mmusculus_gene_ensembl")
#genes = c("Zfp286", "Tmx2")
genes = getLDS(attributes = c("mgi_symbol"), filters = "mgi_symbol", values = M9_MED1_k27ac_A$SYMBOL ,mart = mouse, attributesL = c("hgnc_symbol"), martL = human, uniqueRows=T)
genes
colnames(genes) <- c("SYMBOL", "Hu_SYMBOL")
M9_MED1_k27ac_A_Hu <- merge(M9_MED1_k27ac_A,genes, by="SYMBOL")

```


## loading the microarray
```{r}
MICROAR = "../../../../04_microarray_miR9_GOF_in_MLE12/Improved_Microarray_data_forR2_IMPRO.csv"
cat("Current file name is:",MICROAR,"/n")
mat_MICROAR_sor_ES = read.delim(MICROAR,header=T,check.names=FALSE, stringsAsFactors=FALSE,sep="\t")
name3<- data.frame(colnames(mat_MICROAR_sor_ES))
head (mat_MICROAR_sor_ES)
#mat_MICROAR_sor_ES <- mat_MICROAR_sor_ES[!duplicated(mat_MICROAR_sor_ES$REFSEQ),]
name1<- data.frame(colnames(mat_MICROAR_sor_ES))
df2_MICROAR_u <- subset(mat_MICROAR_sor_ES,FC_20vs_22_miR9_GOF_vs_Schr >= 1.001)
df2_MICROAR_d <- subset(mat_MICROAR_sor_ES, FC_20vs_22_miR9_GOF_vs_Schr <= 0.9)

df2_MICROAR_diff <- rbind(df2_MICROAR_u,df2_MICROAR_d)
df2_MICROAR_diff = subset(df2_MICROAR_diff, SYMBOL= " ", select= c("FC_20vs_22_miR9_GOF_vs_Schr","REFSEQ","SYMBOL"))
colnames(df2_MICROAR_diff) <- c("mir9_GOF_Log2FC","REFSEQ", "SYMBOL")

#M9_MED1_k27ac_A$REFSEQ <- M9_MED1_k27ac_A$`Nearest Refseq`
M9_MED1_k27ac_A_vs_MICROA <- merge(M9_MED1_k27ac_A_Hu,df2_MICROAR_diff, by="SYMBOL")

write.xlsx(M9_MED1_k27ac_A_vs_MICROA,file=paste(PORT1,PROJECT,"_PNHDAs_2.xls",sep=""))
write.table(M9_MED1_k27ac_A_vs_MICROA,file=paste(PORT1,PROJECT,"_PNHDAs_2.txt",sep=""),sep="\t",row.names = F,col.names=T,dec=".")
```



### 
###venn diagram
```{r}
PORT="../fromR_v_Rna/"
  #length(unique(df2_sor_ES_d$SYMBOL))
D0=paste(PORT,"00Venn",PROJECT, ".tiff",sep="")
LL=0.03
TT=0.7
PP=c(0.5, 0.80)
PP2=c(0.5, 0.90)
MM=0.35
set.seed(1)
#df2_sor_ES_diff_RNA_u$SY
#H2Bub_ES<- data.frame(df2_H2Bub_ES_diff_RNA_u$SYMBOL)
#H2Bub_ES<- na.omit(H2Bub_ES$df2_H2Bub_ES_diff_RNA_u.SYMBOL)
require(VennDiagram)
venn.plot <- venn.diagram(
    list(M9 =df2_M9_TSS2_u$SYMBOL, C4 = df2_MED1_TSS2_u$SYMBOL, k27ac= df2_k27ac_TSS2_u$SYMBOL), 
  D0,
  col = "transparent",
  fill = c("darkgreen","violet","cyan"),
  alpha = TT,
  label.col = c("black", "white", "black", "black","black", "black" ,"black" ),
  cex = 1.5,
  fontfamily = "serif",
  fontface = "bold",
  cat.col = c("darkblue", "darkblue", "darkblue"),
  cat.cex = 1.5,
  cat.pos = 0,
  cat.dist = LL,
  cat.fontfamily = "serif",
  rotation.degree = 180,
  margin = MM,
  print.mode="raw",
  hyper.test = T,
    resolution =600,
  main=D0,
    main.cex=1,  main.pos =PP
  
);
```

###venn diagram  4 samples
```{r}
PORT="../fromR_v_Rna/"
  #length(unique(df2_sor_ES_d$SYMBOL))
D0=paste(PORT,"00Venn",PROJECT, "_W_PNHDAS.tiff",sep="")
LL=0.3
TT=0.7
PP=c(0.5, 0.80)
PP2=c(0.5, 0.90)
MM=0.35
set.seed(1)
#df2_sor_ES_diff_RNA_u$SY
#H2Bub_ES<- data.frame(df2_H2Bub_ES_diff_RNA_u$SYMBOL)
#H2Bub_ES<- na.omit(H2Bub_ES$df2_H2Bub_ES_diff_RNA_u.SYMBOL)
require(VennDiagram)
venn.plot <- venn.diagram(
    list(M9 =df2_M9_TSS2_u$SYMBOL, C4 = df2_MED1_TSS2_u$SYMBOL, k27ac= df2_k27ac_TSS2_u$SYMBOL,
         PNH=mat_PNHADs_sor_ES$SYMBOL), 
  D0,
  col = "transparent",
  fill = c("darkgreen","violet","cyan","gray"),
  alpha = TT,
  label.col = c("black", "black", "black", "black","black", "white" ,"black",
                "black", "black", "black", "black","black", "black" ,"black","black"),
  cex = 1.5,
  fontfamily = "serif",
  fontface = "bold",
  cat.col = c("darkblue", "darkblue", "darkblue", "darkblue"),
  cat.cex = 1.5,
  cat.pos = 0,
  cat.dist = LL,
  cat.fontfamily = "serif",
  rotation.degree = 180,
  margin = MM,
  print.mode="raw",
  hyper.test = T,
    resolution =600,
  main=D0,
    main.cex=1,  main.pos =PP
  
);
```


### GO analysis not expression
```{r, echo=FALSE}

#wp.hs.gmt <- rWikiPathways::downloadPathwayArchive(organism="Homo sapiens", format = "gmt")

differ_2<-M9_MED1_k27ac_A

differ_3 <- bitr(differ_2$SYMBOL, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Mm.eg.db")

differ_4 = merge(differ_3,differ_2, by= "SYMBOL")
#colnames(differ_4)<- c("SYMBOL","Entrez","logFC","group",name4)

differ_4_u <- differ_4[!duplicated(differ_4$SYMBOL),]
#colnames(differ_4_u)<- c("SYMBOL","Entrez","logFC","CLASS")



differ_4d = subset(differ_4, group=="02nO_PNHA")
differ_4u = subset(differ_4, group=="01in_PNHA")



differ_5 = subset(differ_4, SYMBOL= " ", select= c("ENTREZID","group"))

formula_resddBGI11FC1_25_1_5_bonfe <- compareCluster(ENTREZID~group, data=differ_5,fun = "enrichGO",OrgDb="org.Mm.eg.db",
                                              ont           = "BP",
                                              pAdjustMethod = "bonferroni",
                                              pvalueCutoff  = 0.05,
                                              qvalueCutoff  = 0.05,
                                              readable = T)

#ego <- DOSE::setReadable(formula_resddBGI11FC1_25_1_5_bonfe, OrgDb = org.Mm.eg.db)
#ego@compareClusterResult
GO00<- dotplot(formula_resddBGI11FC1_25_1_5_bonfe,showCategory=10, title=paste(PROJECT,"_bonfe_Deseq2_test"))
## fc 1.25 and 1.5
formula_diff_FDR <- compareCluster(ENTREZID~group, data=differ_5,fun = "enrichGO",OrgDb="org.Mm.eg.db",
                                   ont           = "BP",
                                   pAdjustMethod = "fdr",
                                   pvalueCutoff  = 0.01,
                                   qvalueCutoff  = 0.01,
                                   readable = T)

GO01<- dotplot(formula_diff_FDR,showCategory=10, title=paste(PROJECT,"_FDR_Deseq2_test"))
print(GO01)
#ego@compareClusterResult


ewp.d1e <- clusterProfiler::enrichGO(
        gene=differ_4d[[2]],
        pAdjustMethod="BH",
       keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
         ont="BP",     
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )


ewp.u1e <- clusterProfiler::enrichGO(
        gene=differ_4u[[2]],
        pAdjustMethod="BH",
        keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
        ont="BP",
              
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )


GO06<- dotplot(ewp.d1e, showCategory = 10, title=paste(PROJECT,"_enrichGO_D_P"))
GO07<- dotplot(ewp.u1e, showCategory = 10, title=paste(PROJECT,"_enrichGO_U_P"))


ewp.d <- setReadable(ewp.d1e, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")
ewp.u <- setReadable(ewp.u1e, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")



ewp.d@result$FDR2<- -log10(ewp.d@result$p.adjust )
GO04b<- ggplot(ewp.d@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_D_p")) + theme_classic() +
    theme(axis.text=element_text(size=11))
 
ewp.u@result$FDR2<- -log10(ewp.u@result$p.adjust )
GO04c<- ggplot(ewp.u@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_U_P")) + theme_classic() +
    theme(axis.text=element_text(size=11))



################################################################################################



GO04d<- cnetplot(ewp.d1e, showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_P"))
GO04e <- cnetplot(ewp.u1e,showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_U_p")) 

#GO04dnp<- cnetplot(ewp.d1enp, showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_nP"))



GO010<- heatplot(ewp.d1e, foldChange=differ_4d$logFC)+ ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_p"))
GO010b<- heatplot(ewp.u1e, foldChange=differ_4d$logFC) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_U_p"))

GO011<- emapplot(ewp.d1e,showCategory = 5) 
GO012<- emapplot(ewp.u1e,showCategory = 5)


{
pdf(file=paste(PORT1,PROJECT,"FIGURES_GOs_RPKM_Q1.pdf" ), width=15, height=8)  

print(GO00)
print(GO01)
#print(GO02)
#print(GO03)
#print(GO04)
#print(GO05)
print(GO04b)
print(GO04c)
print(GO04d)
#print(GO04dnp)
print(GO04e)
print(GO010)
print(GO010b)
#print(GO010np)

print(GO011)
print(GO012)
 }
 
 dev.off()
#head(ewp.wiki)
 PA="./fromR"
 #  egoFDR <- setReadable(formula_diff_FDR, OrgDb = org.Mm.eg.db)
  egoFDR2<- subset(formula_diff_FDR@compareClusterResult, ID=" ", select=c("Cluster","ID","p.adjust"))
  egoFDR3d<- subset(ewp.d1e@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  egoFDR3u<- subset(ewp.u1e@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  
  egoFDR3u$REG<-"inPNHDA"
  egoFDR3d$REG<- "noPNHDA"
   
  egoFDR3diff <- rbind(egoFDR3d,egoFDR3u)
  write.xlsx(formula_diff_FDR@compareClusterResult,file=paste(PORT,'CP1vs_E10_5_FIGURES_GOs_FDR_MATRIX.xlsx'))
#    write.xlsx(ewp.wiki,file='./fromR/00E10_5_dob25_Rnf2_DOWN_WIKI_MATRIX.xlsx')
 #  write.xlsx(ewp.wikiU,file='./fromR/00E10_5_dob25_Rnf2_UP_WIKI_MATRIX.xlsx')
   
 
 write.xlsx(ewp.d1e,file=paste(PORT1,PROJECT,"_DOWN_GOs_FDR_enrichGO.xlsx"))
     write.xlsx(ewp.u1e,file=paste(PORT1,PROJECT,"_GOs_FDR_enrichGO.xlsx"))
  write.xlsx(egoFDR3diff,file=paste(PORT1,PROJECT,"5_FDR_MATRIX_forREVIGO.xls"))
    write.xlsx(differ_4,file=paste(PORT1,PROJECT,"SYMBOL_GROUPS.xls"))


 

```


### GO analysis not expression
```{r, echo=FALSE}

#wp.hs.gmt <- rWikiPathways::downloadPathwayArchive(organism="Homo sapiens", format = "gmt")

differ_2<-M9_MED1_k27ac_A_vs_MICROA

differ_3 <- bitr(differ_2$SYMBOL, fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Mm.eg.db")

differ_4 = merge(differ_3,differ_2, by= "SYMBOL")
#colnames(differ_4)<- c("SYMBOL","Entrez","logFC","group",name4)

differ_4_u <- differ_4[!duplicated(differ_4$SYMBOL),]
#colnames(differ_4_u)<- c("SYMBOL","Entrez","logFC","CLASS")


differ_4d = subset(differ_4, group=="02nO_PNHA")
differ_4u = subset(differ_4, group=="01in_PNHA")



differ_5 = subset(differ_4, SYMBOL= " ", select= c("ENTREZID","group"))

formula_resddBGI11FC1_25_1_5_bonfe <- compareCluster(ENTREZID~group, data=differ_5,fun = "enrichGO",OrgDb="org.Mm.eg.db",
                                              ont           = "BP",
                                              pAdjustMethod = "bonferroni",
                                              pvalueCutoff  = 0.05,
                                              qvalueCutoff  = 0.05,
                                              readable = T)

#ego <- DOSE::setReadable(formula_resddBGI11FC1_25_1_5_bonfe, OrgDb = org.Mm.eg.db)
#ego@compareClusterResult
GO00<- dotplot(formula_resddBGI11FC1_25_1_5_bonfe,showCategory=10, title=paste(PROJECT,"_bonfe_Deseq2_test"))
## fc 1.25 and 1.5
formula_diff_FDR <- compareCluster(ENTREZID~group, data=differ_5,fun = "enrichGO",OrgDb="org.Mm.eg.db",
                                   ont           = "BP",
                                   pAdjustMethod = "fdr",
                                   pvalueCutoff  = 0.01,
                                   qvalueCutoff  = 0.01,
                                   readable = T)

GO01<- dotplot(formula_diff_FDR,showCategory=10, title=paste(PROJECT,"_FDR_Deseq2_test"))
print(GO01)
#ego@compareClusterResult


ewp.d1e <- clusterProfiler::enrichGO(
        gene=differ_4d[[2]],
        pAdjustMethod="BH",
       keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
         ont="BP",     
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )


ewp.u1e <- clusterProfiler::enrichGO(
        gene=differ_4u[[2]],
        pAdjustMethod="BH",
        keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
        ont="BP",
              
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )


GO06<- dotplot(ewp.d1e, showCategory = 10, title=paste(PROJECT,"_enrichGO_NO_PNHA_DIFF_EX"))
GO07<- dotplot(ewp.u1e, showCategory = 10, title=paste(PROJECT,"_enrichGO_IN_PNHA_DIFF_EX"))


ewp.d <- setReadable(ewp.d1e, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")
ewp.u <- setReadable(ewp.u1e, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")



ewp.d@result$FDR2<- -log10(ewp.d@result$p.adjust )
GO04b<- ggplot(ewp.d@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_NO_PNHA")) + theme_classic() +
    theme(axis.text=element_text(size=11))
 
ewp.u@result$FDR2<- -log10(ewp.u@result$p.adjust )
GO04c<- ggplot(ewp.u@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_INPNHA")) + theme_classic() +
    theme(axis.text=element_text(size=11))



################################################################################################
GO04d<- cnetplot(ewp.d1e, showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_NO_PNHA"))
GO04e <- cnetplot(ewp.u1e,showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_IN_PNHA")) #GO04dnp<- cnetplot(ewp.d1enp, showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_nP"))

GO010<- heatplot(ewp.d1e, foldChange=differ_4d$logFC)+ ggtitle(paste(PROJECT,"enrichGO_TOP5_no_PNHA"))

GO010b<- heatplot(ewp.u1e, foldChange=differ_4d$logFC) + ggtitle(paste(PROJECT,"enrichGO_TOP5_IN_PNHA"))

GO011<- emapplot(ewp.d1e,showCategory = 5) 
GO012<- emapplot(ewp.u1e,showCategory = 5)


{
pdf(file=paste(PORT1,PROJECT,"FIGURES_GOs_RPKM_Q1_W_DIFF_EXPRE.pdf" ), width=15, height=8)  

print(GO00)
print(GO01)
#print(GO02)
#print(GO03)
#print(GO04)
#print(GO05)
print(GO04b)
print(GO04c)
print(GO04d)
#print(GO04dnp)
print(GO04e)
print(GO010)
print(GO010b)
#print(GO010np)

print(GO011)
print(GO012)
 }
 
 dev.off()
#head(ewp.wiki)
 PA="./fromR"
 #  egoFDR <- setReadable(formula_diff_FDR, OrgDb = org.Mm.eg.db)
  egoFDR2<- subset(formula_diff_FDR@compareClusterResult, ID=" ", select=c("Cluster","ID","p.adjust"))
  egoFDR3d<- subset(ewp.d1e@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  egoFDR3u<- subset(ewp.u1e@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  
  egoFDR3u$REG<-"inPNHDA"
  egoFDR3d$REG<- "noPNHDA"
   
  egoFDR3diff <- rbind(egoFDR3d,egoFDR3u)
#  write.xlsx(formula_diff_FDR@compareClusterResult,file=paste(PORT,'CP1vs_E10_5_FIGURES_GOs_FDR_MATRIX.xlsx'))
#    write.xlsx(ewp.wiki,file='./fromR/00E10_5_dob25_Rnf2_DOWN_WIKI_MATRIX.xlsx')
 #  write.xlsx(ewp.wikiU,file='./fromR/00E10_5_dob25_Rnf2_UP_WIKI_MATRIX.xlsx')
   
 
write.xlsx(ewp.d1e,file=paste(PORT1,PROJECT,"_DOWN_GOs_FDR_enrichGO_w_EXPR.xlsx"))
write.xlsx(ewp.u1e,file=paste(PORT1,PROJECT,"_GOs_FDR_enrichGO_w_EXPR.xlsx"))
write.xlsx(egoFDR3diff,file=paste(PORT1,PROJECT,"5_FDR_MATRIX_forREVIGO_w_EXPR.xls"))
write.xlsx(differ_4,file=paste(PORT1,PROJECT,"SYMBOL_GROUPS_w_EXPR.xls"))


 
 

```




######write log2fc 0.58 and P0-05





# matrix for GO targets and not targets!!
```{r}
length(unique(CP1vs_H2Bub_ES$SYMBOL))
length(unique(GNdiff$SYMBOL))
GNdiff1<- merge(GNdiff,df2_sor_ES_diff_RNA_u, by="SYMBOL")
CP1vs_H2Bub_ES$CLASS <- "P"
GNdiff1$CLASS <- "nP"
CP1_v_H2Bub_ES_se<- subset(CP1vs_H2Bub_ES, SYMBOL=" ",select=c("SYMBOL","log2FoldChange", "CLASS",name4))

GNdiff1b<- subset(GNdiff1, SYMBOL=" ",select=c("SYMBOL", "log2FoldChange","CLASS",name4))

```


### GO analysis
```{r, echo=FALSE}

#wp.hs.gmt <- rWikiPathways::downloadPathwayArchive(organism="Homo sapiens", format = "gmt")

differ_2<- rbind(CP1_v_H2Bub_ES_se,GNdiff1b)

differ_3 <- bitr(differ_2[,1], fromType="SYMBOL", toType=c("ENTREZID"), OrgDb="org.Mm.eg.db")

differ_4 = merge(differ_3,differ_2, by= "SYMBOL")
colnames(differ_4)<- c("SYMBOL","Entrez","logFC","group",name4)

differ_4_u <- differ_4[!duplicated(differ_4$SYMBOL),]
#colnames(differ_4_u)<- c("SYMBOL","Entrez","logFC","CLASS")
differ_4$group[differ_4$logFC <= LOGD & differ_4$group == "P"] <- "01d_P"
differ_4$group[differ_4$logFC <= LOGD & differ_4$group == "nP"] <- "02d_nP"

differ_4$group[differ_4$logFC >= LOGU & differ_4$group == "P"] <- "03u_P"
differ_4$group[differ_4$logFC >= LOGU & differ_4$group == "nP"] <- "04u_nP"



differ_4d = subset(differ_4, group=="01d_P")
differ_4u = subset(differ_4, group=="03u_P")
differ_4dnp = subset(differ_4, group=="02d_nP")
differ_4unp = subset(differ_4, group=="04u_nP")
length(unique(differ_4dnp$SYMBOL))


differ_5 = subset(differ_4, gene_name= " ", select= c("Entrez","group"))

formula_resddBGI11FC1_25_1_5_bonfe <- compareCluster(Entrez~group, data=differ_5,fun = "enrichGO",OrgDb="org.Mm.eg.db",
                                              ont           = "BP",
                                              pAdjustMethod = "bonferroni",
                                              pvalueCutoff  = 0.05,
                                              qvalueCutoff  = 0.05,
                                              readable = T)

#ego <- DOSE::setReadable(formula_resddBGI11FC1_25_1_5_bonfe, OrgDb = org.Mm.eg.db)
#ego@compareClusterResult
GO00<- dotplot(formula_resddBGI11FC1_25_1_5_bonfe,showCategory=10, title=paste(PROJECT,"_bonfe_Deseq2_test"))
## fc 1.25 and 1.5
formula_diff_FDR <- compareCluster(Entrez~group, data=differ_5,fun = "enrichGO",OrgDb="org.Mm.eg.db",
                                   ont           = "BP",
                                   pAdjustMethod = "fdr",
                                   pvalueCutoff  = 0.01,
                                   qvalueCutoff  = 0.01,
                                   readable = T)

GO01<- dotplot(formula_diff_FDR,showCategory=10, title=paste(PROJECT,"_FDR_Deseq2_test"))
print(GO01)
#ego@compareClusterResult


ewp.d1e <- clusterProfiler::enrichGO(
        gene=differ_4d[[2]],
        pAdjustMethod="BH",
       keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
         ont="BP",     
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )

ewp.d1enp <- clusterProfiler::enrichGO(
        gene=differ_4dnp[[2]],
        pAdjustMethod="BH",
       keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
         ont="BP",     
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )
ewp.u1e <- clusterProfiler::enrichGO(
        gene=differ_4u[[2]],
        pAdjustMethod="BH",
        keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
        ont="BP",
              
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )
ewp.u1enp <- clusterProfiler::enrichGO(
        gene=differ_4unp[[2]],
        pAdjustMethod="BH",
        keyType = "ENTREZID",
        OrgDb="org.Mm.eg.db",
        readable = T,
        ont="BP",
              
        pvalueCutoff = 0.05, #p.adjust cutoff; relaxed for demo purposes
        )


GO06<- dotplot(ewp.d1e, showCategory = 10, title=paste(PROJECT,"_enrichGO_D_P"))
GO07<- dotplot(ewp.u1e, showCategory = 10, title=paste(PROJECT,"_enrichGO_U_P"))

GO06b<- dotplot(ewp.d1enp, showCategory = 10, title=paste(PROJECT,"_enrichGO_D_nP"))
GO07b<- dotplot(ewp.u1enp, showCategory = 10, title=paste(PROJECT,"_enrichGO_U_nP"))
GO06b

ewp.d <- setReadable(ewp.d1e, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")
ewp.u <- setReadable(ewp.u1e, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")

ewp.dnp <- setReadable(ewp.d1enp, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")
ewp.unp <- setReadable(ewp.u1enp, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")


ewp.d@result$FDR2<- -log10(ewp.d@result$p.adjust )
GO04b<- ggplot(ewp.d@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_D_p")) + theme_classic() +
    theme(axis.text=element_text(size=11))
 
ewp.u@result$FDR2<- -log10(ewp.u@result$p.adjust )
GO04c<- ggplot(ewp.u@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_U_P")) + theme_classic() +
    theme(axis.text=element_text(size=11))

###################################     NO PEAKS      #######################################
ewp.dnp@result$FDR2<- -log10(ewp.dnp@result$p.adjust )
GO04bnp <- ggplot(ewp.dnp@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_D_np")) + theme_classic() +
    theme(axis.text=element_text(size=11))
 
ewp.unp@result$FDR2<- -log10(ewp.unp@result$p.adjust )
GO04cnp <- ggplot(ewp.unp@result[1:10,], aes(x=reorder(Description, FDR2),FDR2,  fill=FDR2)) +
    geom_bar(stat = "identity") +
    coord_flip() +
    scale_fill_continuous(low="blue", high="deeppink") +
    labs(x = "", y = "", fill = "FDR2",title = paste(PROJECT,"_TP10_enrichGO_U_nP")) + theme_classic() +
    theme(axis.text=element_text(size=11))

################################################################################################



GO04d<- cnetplot(ewp.d1e, showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_P"))
GO04e <- cnetplot(ewp.u1e,showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_U_p")) 

#GO04dnp<- cnetplot(ewp.d1enp, showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_nP"))
GO04enp<- cnetplot(ewp.u1enp,showCategory = 3) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_U_np"))


GO010<- heatplot(ewp.d1e, foldChange=differ_4d$logFC)+ ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_p"))
GO010b<- heatplot(ewp.u1e, foldChange=differ_4d$logFC) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_U_p"))
GO010np<- heatplot(ewp.d1enp, foldChange=differ_4d$logFC)+ ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_D_np"))
GO010bnp<- heatplot(ewp.u1enp, foldChange=differ_4d$logFC) + ggtitle(paste(PROJECT,"enrichGO_TOP5_BP_U_np"))

GO011<- emapplot(ewp.d1e,showCategory = 5) 
GO012<- emapplot(ewp.u1e,showCategory = 5)


{
pdf(file=paste(PORT1,PROJECT,"FIGURES_GOs_RPKM_Q1.pdf" ), width=15, height=8)  

print(GO00)
print(GO01)
#print(GO02)
#print(GO03)
#print(GO04)
#print(GO05)
print(GO04b)
print(GO04bnp)
print(GO04c)
print(GO04cnp)
print(GO04d)
#print(GO04dnp)
print(GO04e)
print(GO04enp)
print(GO010)
print(GO010b)
#print(GO010np)
print(GO010bnp)

print(GO011)
print(GO012)
 }
 
 dev.off()
#head(ewp.wiki)
 PA="./fromR"
 #  egoFDR <- setReadable(formula_diff_FDR, OrgDb = org.Mm.eg.db)
  egoFDR2<- subset(formula_diff_FDR@compareClusterResult, ID=" ", select=c("Cluster","ID","p.adjust"))
  egoFDR3d<- subset(ewp.d1e@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  egoFDR3u<- subset(ewp.u1e@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  egoFDR3dnp<- subset(ewp.d1enp@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  egoFDR3unp<- subset(ewp.u1enp@result, ID=" ", select=c("ID","p.adjust","pvalue","Description","geneID"))
  
  
  egoFDR3u$REG<-"u_p"
  egoFDR3d$REG<- "d_P"
   egoFDR3unp$REG<-"u_np"
  egoFDR3dnp$REG<- "d_nP"
  egoFDR3diff <- rbind(egoFDR3d,egoFDR3u,egoFDR3unp,egoFDR3dnp)
  write.xlsx(formula_diff_FDR@compareClusterResult,file=paste(PORT,'CP1vs_E10_5_FIGURES_GOs_FDR_MATRIX.xlsx'))
#    write.xlsx(ewp.wiki,file='./fromR/00E10_5_dob25_Rnf2_DOWN_WIKI_MATRIX.xlsx')
 #  write.xlsx(ewp.wikiU,file='./fromR/00E10_5_dob25_Rnf2_UP_WIKI_MATRIX.xlsx')
   
 
 write.xlsx(ewp.d1e,file=paste(PORT1,PROJECT,"_DOWN_GOs_FDR_enrichGO.xlsx"))
     write.xlsx(ewp.u1e,file=paste(PORT1,PROJECT,"_GOs_FDR_enrichGO.xlsx"))
  write.xlsx(egoFDR3diff,file=paste(PORT1,PROJECT,"5_FDR_MATRIX_forREVIGO.xls"))
    write.xlsx(differ_4,file=paste(PORT1,PROJECT,"SYMBOL_GROUPS.xls"))


 

```

######from from here HEATMAP

```{r,echo=FALSE}

mat_esc_TMM<-differ_4
library(ComplexHeatmap)
library(circlize)
g1<- c("c1","c2","ko1","ko2")
### mat esc_TMM ####
#mat_esc_TMM <- list(mat_LA2,mat_LAbg) %>%
#  Reduce(function(dtf1,dtf2) inner_join(dtf1,dtf2,by="SYMBOL"), .)
mat_esc_TMM <- mat_esc_TMM[!duplicated(mat_esc_TMM$SYMBOL),]
mat_esc_TMM <- mat_esc_TMM[order(mat_esc_TMM$group,decreasing=F),]

colnames(mat_esc_TMM)<- c("SYMBOL","Entrez","logFC","group",G1)
#mat_esc_TMM <- subset(mat_esc_TMM, SYMBOL=" " , select= c("SYMBOL","Ctr1","Ctr2","Ctr4","LA_KO1","LA_KO2","LA_KO3","feat"))

############ prepare data matrix for heatmap  ##################
rownames(mat_esc_TMM)<- mat_esc_TMM$SYMBOL

gly_esc_TMM <-  as.matrix(mat_esc_TMM[,5:ncol(mat_esc_TMM)])
mat_esc_TMM_heat = t(scale(t(gly_esc_TMM)))
#colnames(mat_esc_TMM_heat)<- g1x
HHa<- cbind(mat_esc_TMM,mat_esc_TMM_heat)
type = gsub("s//d+_", "", colnames(mat_esc_TMM_heat))
type2<- t(data.frame(type))
type2
type
summary(mat_esc_TMM_heat)
L=-2
M=2
CC= c("#4d9221", "#F7F7F7","#c51b7d")
hesc_TMM = HeatmapAnnotation(df = data.frame(type = type),col = list(type = c(C1= CCTR,C2= CCTR, ES_KO1=CCKO, ES_KO2=CCKO)))
FIELD<- HHa$group
#FIELD2<- mat_esc_TMM$feature
#TF<- mat_esc_TMM$TF




####  "Gluta"="cyan", "FAO"="gold", "1Carbon"="pink")
h<-rowAnnotation(df =data.frame(FIELD), col = list(FIELD = c("01d_P" =  "darkgreen", "02d_nP" = "cyan",
                                                             "03u_P"= "deeppink",
                                                             "04u_nP"="purple")))
#hr<-rowAnnotation(df =data.frame(FIELD2), col = list(FIELD2 = c("01TF_SHF" =  "purple", "02Cell_cy_SHF" = "red",
  #                                                               "02PI3K-Akt_SHF" = "cyan",
  #                                                              "03cGMP-PKG_FHF" = "blue",
  #                                                              "00TF_FHF" = "gray",
  #                                                              "03Insu_FHF" = "purple",
  #                                                              "05cell_sur_FHF"="pink")))

#hrTF<-rowAnnotation(df =data.frame(TF), col = list(TF = c("TF_SHF" =  "purple", 
  #                                                              "TF_FHF" = "gray",
  #                                                              "SIG_SHF" = "red",
 ##                                                               "SIG_FHF" ="cyan",
  #                                                     "cell_sur_FHF"="pink")))


IMPORT=column_order = order(as.numeric(gsub("column", "", colnames(HHa[,9:12]))))
KM=4

{
  pdf(file=paste(PORT1, PROJECT,"_HEATMAP_RPKM_Q1.pdf"), width=6, height=10) 
    set.seed(1)
  Hesc_TMM<- Heatmap(HHa[,9:12] , name="zcore", cluster_columns = F,cluster_rows = T, col=colorRamp2(c(L, 0, M), CC),top_annotation = hesc_TMM,left_annotation = h, show_row_names = T,  row_names_gp = gpar(fontsize = 5),  show_column_names = FALSE,km= " ",column_order = IMPORT,column_title=paste(PROJECT))
   draw(Hesc_TMM, heatmap_legend_side = "left", annotation_legend_side = "left",
       merge_legend = TRUE)
  Hesc_TMM2<- Heatmap(HHa[,9:12] , name="zcore", cluster_columns = F,cluster_rows = F, col=colorRamp2(c(L, 0, M),CC),top_annotation = hesc_TMM,left_annotation = h, show_row_names = T,  row_names_gp = gpar(fontsize = 5),  show_column_names = FALSE,column_order = IMPORT, column_title=paste(PROJECT))
   draw(Hesc_TMM2, heatmap_legend_side = "left", annotation_legend_side = "left",
       merge_legend = TRUE)
  #print(Hesc_TMM2)
  
}
dev.off()
```




